from __future__ import annotations

from env.models import TaskSummary


TASK_ORDER = [
    "task_1_idle_capacity_cleanup",
    "task_2_carbon_aware_rebalancing",
    "task_3_resilient_multi_objective_dispatch",
]


TASKS = {
    "task_1_idle_capacity_cleanup": {
        "task_id": "task_1_idle_capacity_cleanup",
        "name": "Idle Capacity Cleanup",
        "difficulty": "easy",
        "objective": "Shut down idle GPU servers without disrupting any live workloads.",
        "description": (
            "A capacity planner notices several expensive GPU hosts sitting idle after "
            "batch jobs completed. The agent should power them down while preserving "
            "all production workloads."
        ),
        "max_steps": 5,
        "success_threshold": 0.9,
        "low_carbon_regions": ["eu-west"],
        "metadata": {
            "idle_servers": ["us-east-gpu-b", "eu-west-gpu-b"],
        },
        "regions": [
            {
                "region_id": "us-east",
                "label": "US East",
                "carbon_intensity": 0.42,
                "energy_price_usd_per_kwh": 0.11,
                "ambient_temp_c": 27.0,
            },
            {
                "region_id": "eu-west",
                "label": "EU West",
                "carbon_intensity": 0.18,
                "energy_price_usd_per_kwh": 0.13,
                "ambient_temp_c": 20.0,
            },
            {
                "region_id": "ap-south",
                "label": "AP South",
                "carbon_intensity": 0.52,
                "energy_price_usd_per_kwh": 0.09,
                "ambient_temp_c": 31.0,
            },
        ],
        "servers": [
            {
                "server_id": "us-east-gpu-a",
                "label": "US East GPU A",
                "region_id": "us-east",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.2,
                "max_power_kw": 3.2,
                "power_cap_kw": 3.2,
                "thermal_coeff": 12.5,
                "cooling_offset": 3.0,
            },
            {
                "server_id": "us-east-gpu-b",
                "label": "US East GPU B",
                "region_id": "us-east",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.1,
                "max_power_kw": 3.0,
                "power_cap_kw": 3.0,
                "thermal_coeff": 12.0,
                "cooling_offset": 3.0,
            },
            {
                "server_id": "eu-west-gpu-a",
                "label": "EU West GPU A",
                "region_id": "eu-west",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 2.8,
                "power_cap_kw": 2.8,
                "thermal_coeff": 10.5,
                "cooling_offset": 4.0,
            },
            {
                "server_id": "eu-west-gpu-b",
                "label": "EU West GPU B",
                "region_id": "eu-west",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 2.8,
                "power_cap_kw": 2.8,
                "thermal_coeff": 10.5,
                "cooling_offset": 4.0,
            },
            {
                "server_id": "ap-south-gpu-a",
                "label": "AP South GPU A",
                "region_id": "ap-south",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.2,
                "max_power_kw": 3.1,
                "power_cap_kw": 3.1,
                "thermal_coeff": 13.5,
                "cooling_offset": 3.0,
            },
        ],
        "workloads": [
            {
                "workload_id": "prod-forecast",
                "label": "Prod Forecast",
                "gpu_demand": 4.0,
                "priority": "critical",
                "can_migrate": False,
                "allowed_regions": ["us-east"],
                "assigned_server_id": "us-east-gpu-a",
                "initial_server_id": "us-east-gpu-a",
                "target_class": "protect_service",
            },
            {
                "workload_id": "index-refresh",
                "label": "Index Refresh",
                "gpu_demand": 2.0,
                "priority": "medium",
                "can_migrate": False,
                "allowed_regions": ["eu-west"],
                "assigned_server_id": "eu-west-gpu-a",
                "initial_server_id": "eu-west-gpu-a",
                "target_class": "protect_service",
            },
            {
                "workload_id": "nightly-features",
                "label": "Nightly Features",
                "gpu_demand": 3.0,
                "priority": "low",
                "can_migrate": False,
                "allowed_regions": ["ap-south"],
                "assigned_server_id": "ap-south-gpu-a",
                "initial_server_id": "ap-south-gpu-a",
                "target_class": "protect_service",
            },
        ],
    },
    "task_2_carbon_aware_rebalancing": {
        "task_id": "task_2_carbon_aware_rebalancing",
        "name": "Carbon-Aware Rebalancing",
        "difficulty": "medium",
        "objective": (
            "Move flexible workloads from high-carbon capacity into low-carbon regions "
            "without overloading servers or touching the pinned latency workload."
        ),
        "description": (
            "A sustainability team wants overnight retraining jobs moved away from a "
            "dirty grid. The agent can activate greener capacity and migrate only the "
            "flexible workloads."
        ),
        "max_steps": 8,
        "success_threshold": 0.85,
        "low_carbon_regions": ["eu-nordic", "ap-hydro"],
        "metadata": {
            "protected_workloads": ["search-ranker"],
        },
        "regions": [
            {
                "region_id": "us-central",
                "label": "US Central",
                "carbon_intensity": 0.74,
                "energy_price_usd_per_kwh": 0.1,
                "ambient_temp_c": 30.0,
            },
            {
                "region_id": "eu-nordic",
                "label": "EU Nordic",
                "carbon_intensity": 0.12,
                "energy_price_usd_per_kwh": 0.14,
                "ambient_temp_c": 18.0,
            },
            {
                "region_id": "ap-hydro",
                "label": "AP Hydro",
                "carbon_intensity": 0.17,
                "energy_price_usd_per_kwh": 0.09,
                "ambient_temp_c": 22.0,
            },
        ],
        "servers": [
            {
                "server_id": "us-central-a",
                "label": "US Central A",
                "region_id": "us-central",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.2,
                "max_power_kw": 3.2,
                "power_cap_kw": 3.2,
                "thermal_coeff": 12.0,
                "cooling_offset": 3.0,
            },
            {
                "server_id": "us-central-b",
                "label": "US Central B",
                "region_id": "us-central",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.2,
                "max_power_kw": 3.1,
                "power_cap_kw": 3.1,
                "thermal_coeff": 12.0,
                "cooling_offset": 3.0,
            },
            {
                "server_id": "eu-nordic-a",
                "label": "EU Nordic A",
                "region_id": "eu-nordic",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 2.8,
                "power_cap_kw": 2.8,
                "thermal_coeff": 9.5,
                "cooling_offset": 5.0,
            },
            {
                "server_id": "ap-hydro-a",
                "label": "AP Hydro A",
                "region_id": "ap-hydro",
                "status": "off",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 2.9,
                "power_cap_kw": 2.9,
                "thermal_coeff": 10.5,
                "cooling_offset": 4.0,
            },
        ],
        "workloads": [
            {
                "workload_id": "llm-finetune",
                "label": "LLM Finetune",
                "gpu_demand": 4.0,
                "priority": "high",
                "can_migrate": True,
                "allowed_regions": ["us-central", "eu-nordic", "ap-hydro"],
                "assigned_server_id": "us-central-a",
                "initial_server_id": "us-central-a",
                "target_class": "shift_low_carbon",
            },
            {
                "workload_id": "embeddings-batch",
                "label": "Embeddings Batch",
                "gpu_demand": 2.0,
                "priority": "medium",
                "can_migrate": True,
                "allowed_regions": ["us-central", "eu-nordic", "ap-hydro"],
                "assigned_server_id": "us-central-a",
                "initial_server_id": "us-central-a",
                "target_class": "shift_low_carbon",
            },
            {
                "workload_id": "fraud-model-retrain",
                "label": "Fraud Model Retrain",
                "gpu_demand": 3.0,
                "priority": "medium",
                "can_migrate": True,
                "allowed_regions": ["us-central", "eu-nordic", "ap-hydro"],
                "assigned_server_id": "us-central-b",
                "initial_server_id": "us-central-b",
                "target_class": "shift_low_carbon",
            },
            {
                "workload_id": "search-ranker",
                "label": "Search Ranker",
                "gpu_demand": 3.0,
                "priority": "critical",
                "can_migrate": False,
                "allowed_regions": ["us-central"],
                "assigned_server_id": "us-central-b",
                "initial_server_id": "us-central-b",
                "target_class": "protect_service",
            },
        ],
    },
    "task_3_resilient_multi_objective_dispatch": {
        "task_id": "task_3_resilient_multi_objective_dispatch",
        "name": "Resilient Multi-Objective Dispatch",
        "difficulty": "hard",
        "objective": (
            "Reduce carbon, cost, and thermal risk during a heat wave while preserving "
            "reliability for the real-time workloads."
        ),
        "description": (
            "A hot region is suffering both a power price spike and cooling stress. "
            "The agent must rebalance critical, high-priority, and batch workloads "
            "while using power caps carefully."
        ),
        "max_steps": 10,
        "success_threshold": 0.74,
        "low_carbon_regions": ["eu-green", "in-west"],
        "metadata": {
            "hot_regions": ["us-sunbelt"],
            "protected_workloads": ["realtime-chat", "compliance-index"],
        },
        "regions": [
            {
                "region_id": "us-sunbelt",
                "label": "US Sunbelt",
                "carbon_intensity": 0.68,
                "energy_price_usd_per_kwh": 0.18,
                "ambient_temp_c": 35.0,
            },
            {
                "region_id": "eu-green",
                "label": "EU Green",
                "carbon_intensity": 0.1,
                "energy_price_usd_per_kwh": 0.13,
                "ambient_temp_c": 19.0,
            },
            {
                "region_id": "in-west",
                "label": "IN West",
                "carbon_intensity": 0.27,
                "energy_price_usd_per_kwh": 0.09,
                "ambient_temp_c": 26.0,
            },
        ],
        "servers": [
            {
                "server_id": "us-sunbelt-a",
                "label": "US Sunbelt A",
                "region_id": "us-sunbelt",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.2,
                "max_power_kw": 3.4,
                "power_cap_kw": 3.4,
                "thermal_coeff": 13.0,
                "cooling_offset": 3.5,
            },
            {
                "server_id": "us-sunbelt-b",
                "label": "US Sunbelt B",
                "region_id": "us-sunbelt",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.1,
                "max_power_kw": 3.2,
                "power_cap_kw": 3.2,
                "thermal_coeff": 13.0,
                "cooling_offset": 3.0,
            },
            {
                "server_id": "eu-green-a",
                "label": "EU Green A",
                "region_id": "eu-green",
                "status": "active",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 2.8,
                "power_cap_kw": 2.8,
                "thermal_coeff": 9.0,
                "cooling_offset": 5.5,
            },
            {
                "server_id": "in-west-a",
                "label": "IN West A",
                "region_id": "in-west",
                "status": "off",
                "gpu_capacity": 8.0,
                "base_power_kw": 1.0,
                "max_power_kw": 3.0,
                "power_cap_kw": 3.0,
                "thermal_coeff": 10.8,
                "cooling_offset": 4.0,
            },
        ],
        "workloads": [
            {
                "workload_id": "realtime-chat",
                "label": "Realtime Chat",
                "gpu_demand": 4.0,
                "priority": "critical",
                "can_migrate": True,
                "allowed_regions": ["us-sunbelt", "in-west"],
                "assigned_server_id": "us-sunbelt-a",
                "initial_server_id": "us-sunbelt-a",
                "target_class": "protect_service",
            },
            {
                "workload_id": "vision-inference",
                "label": "Vision Inference",
                "gpu_demand": 3.0,
                "priority": "high",
                "can_migrate": True,
                "allowed_regions": ["us-sunbelt", "in-west", "eu-green"],
                "assigned_server_id": "us-sunbelt-a",
                "initial_server_id": "us-sunbelt-a",
                "target_class": "balance_any",
            },
            {
                "workload_id": "batch-analytics",
                "label": "Batch Analytics",
                "gpu_demand": 3.0,
                "priority": "medium",
                "can_migrate": True,
                "allowed_regions": ["us-sunbelt", "eu-green", "in-west"],
                "assigned_server_id": "us-sunbelt-b",
                "initial_server_id": "us-sunbelt-b",
                "target_class": "shift_low_carbon",
            },
            {
                "workload_id": "nightly-etl",
                "label": "Nightly ETL",
                "gpu_demand": 2.0,
                "priority": "low",
                "can_migrate": True,
                "allowed_regions": ["us-sunbelt", "eu-green", "in-west"],
                "assigned_server_id": "us-sunbelt-b",
                "initial_server_id": "us-sunbelt-b",
                "target_class": "shift_low_carbon",
            },
            {
                "workload_id": "compliance-index",
                "label": "Compliance Index",
                "gpu_demand": 2.0,
                "priority": "high",
                "can_migrate": False,
                "allowed_regions": ["eu-green"],
                "assigned_server_id": "eu-green-a",
                "initial_server_id": "eu-green-a",
                "target_class": "protect_service",
            },
        ],
    },
}


def list_task_summaries() -> list[TaskSummary]:
    return [
        TaskSummary(
            task_id=TASKS[task_id]["task_id"],
            name=TASKS[task_id]["name"],
            difficulty=TASKS[task_id]["difficulty"],
            objective=TASKS[task_id]["objective"],
            max_steps=TASKS[task_id]["max_steps"],
            success_threshold=TASKS[task_id]["success_threshold"],
        )
        for task_id in TASK_ORDER
    ]
